from __future__ import annotations

# Language codes supported by the local M2M100 model. Names are shown in the
# Polish interface; the combobox remains editable for API-specific variants.
LANGUAGES: dict[str, str] = {
    "af": "Afrykanerski",
    "am": "Amharski",
    "ar": "Arabski",
    "ast": "Asturyjski",
    "az": "Azerski",
    "ba": "Baszkirski",
    "be": "Białoruski",
    "bg": "Bułgarski",
    "bn": "Bengalski",
    "br": "Bretoński",
    "bs": "Bośniacki",
    "ca": "Kataloński",
    "ceb": "Cebuano",
    "cs": "Czeski",
    "cy": "Walijski",
    "da": "Duński",
    "de": "Niemiecki",
    "el": "Grecki",
    "en": "Angielski",
    "es": "Hiszpański",
    "et": "Estoński",
    "fa": "Perski",
    "ff": "Fulani",
    "fi": "Fiński",
    "fr": "Francuski",
    "fy": "Fryzyjski",
    "ga": "Irlandzki",
    "gd": "Szkocki gaelicki",
    "gl": "Galicyjski",
    "gu": "Gudżarati",
    "ha": "Hausa",
    "he": "Hebrajski",
    "hi": "Hindi",
    "hr": "Chorwacki",
    "ht": "Haitański",
    "hu": "Węgierski",
    "hy": "Ormiański",
    "id": "Indonezyjski",
    "ig": "Igbo",
    "ilo": "Iloko",
    "is": "Islandzki",
    "it": "Włoski",
    "ja": "Japoński",
    "jv": "Jawajski",
    "ka": "Gruziński",
    "kk": "Kazachski",
    "km": "Khmerski",
    "kn": "Kannada",
    "ko": "Koreański",
    "lb": "Luksemburski",
    "lg": "Ganda",
    "ln": "Lingala",
    "lo": "Laotański",
    "lt": "Litewski",
    "lv": "Łotewski",
    "mg": "Malgaski",
    "mk": "Macedoński",
    "ml": "Malajalam",
    "mn": "Mongolski",
    "mr": "Marathi",
    "ms": "Malajski",
    "my": "Birmański",
    "ne": "Nepalski",
    "nl": "Niderlandzki",
    "no": "Norweski",
    "ns": "Sotho północny",
    "oc": "Oksytański",
    "or": "Orija",
    "pa": "Pendżabski",
    "pl": "Polski",
    "ps": "Paszto",
    "pt": "Portugalski",
    "ro": "Rumuński",
    "ru": "Rosyjski",
    "sd": "Sindhi",
    "si": "Syngaleski",
    "sk": "Słowacki",
    "sl": "Słoweński",
    "so": "Somalijski",
    "sq": "Albański",
    "sr": "Serbski",
    "ss": "Suazi",
    "su": "Sundajski",
    "sv": "Szwedzki",
    "sw": "Suahili",
    "ta": "Tamilski",
    "th": "Tajski",
    "tl": "Tagalski",
    "tn": "Tswana",
    "tr": "Turecki",
    "uk": "Ukraiński",
    "ur": "Urdu",
    "uz": "Uzbecki",
    "vi": "Wietnamski",
    "wo": "Wolof",
    "xh": "Xhosa",
    "yi": "Jidysz",
    "yo": "Joruba",
    "zh": "Chiński",
    "zu": "Zulu",
}


def language_name(code: str) -> str:
    return LANGUAGES.get(code.lower(), code.upper())


def language_options() -> list[str]:
    return [f"{name} ({code})" for code, name in sorted(LANGUAGES.items(), key=lambda x: x[1])]


def parse_language_option(value: str) -> str:
    value = value.strip()
    if value in {"", "—"}:
        return ""
    if value.endswith(")") and "(" in value:
        return value.rsplit("(", 1)[1][:-1].strip().lower()
    return value.lower().replace("_", "-")
